export enum EventType {
   ACCEPT = 'ACCEPT',
	 CREATE = 'CREATE',
	 DELETE = 'DELETE',
	 UPDATE = 'UPDATE',
	 TRIGGER_CANCEL = 'TRIGGER_CANCEL',
	 TRIGGER_DELETE = 'TRIGGER_DELETE',
	 TRIGGER_DEPLOY = 'TRIGGER_DEPLOY',
	 TRIGGER_REDEPLOY = 'TRIGGER_REDEPLOY',
	 TRIGGER_STOP = 'TRIGGER_STOP',
	 TRIGGER_RESTART = 'TRIGGER_RESTART' 
}